name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    strategy:
      matrix:
        os:
          [
            macos-latest,
            macos-26-intel,
            ubuntu-latest,
            ubuntu-24.04-arm,
            windows-latest,
            windows-11-arm,
          ]
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Determine build environment
        id: build-env
        run: |
          echo "env=${{ contains(github.ref_name, '-canary') && 'canary' || 'stable' }}" >> $GITHUB_OUTPUT

      - name: Build app
        run: bun run build:${{ steps.build-env.outputs.env == 'canary' && 'canary' || 'stable' }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          draft: true
          prerelease: ${{ steps.build-env.outputs.env == 'canary' }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
